version: "3"

services:
  dito-mongodb:
    image: docker.io/pdropaiva/dito-mongo:0.0.1
    volumes:
      - ./mongo/data:/data/db
    container_name: "dito-mongodb"
    environment:
      - MONGO_INITDB_DATABASE=admin
  dito-api:
    image: docker.io/pdropaiva/dito-api:0.0.2
    container_name: "dito-api"
    ports:
      - 5000:80
    links:
      - dito-mongodb:dito-mongodb
  dito-autocomplete:
    image: docker.io/pdropaiva/dito-autocomplete:0.0.4
    container_name: "dito-autocomplete"
    ports:
      - 8080:80
    links:
      - dito-api:dito-api
