---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: dito-api
  name: dito-api
spec:
  ports:
    - port: 80
      name: "rest"
      targetPort: 5000
    - port: 5000
      name: "private"
      targetPort: 5000
  selector:
    name: dito-api
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dito-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: dito-api
    spec:
      containers:
      - name: dito-api
        image: docker.io/pdropaiva/dito-api:0.0.2
        ports:
        - containerPort: 5000
