---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: dito-mongodb
  name: dito-mongodb
spec:
  ports:
    - port: 80
      name: "rest"
      targetPort: 27017
    - port: 27017
      name: "private"
      targetPort: 27017
  selector:
    name: dito-mongodb
  type: LoadBalancer
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dito-mongodb-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dito-mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dito-mongodb
    spec:
      containers:
      - name: dito-mongodb
        image: docker.io/mongo:3.6
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: dito-mongodb-storage
            mountPath: /data/db
      volumes:
        - name: dito-mongodb-storage
          persistentVolumeClaim:
            claimName: dito-mongodb-claim
